### ISSUE TITLE
Where could I found more information about gpcp?

### ISSUE THREAD

**Issue by ruanjiaxing** [k-john-gough/gpcp#15]
For example, the API docs and what is and how to use the scripts in the bin directory. The documentation directory only has an Oberon report (language specification) but no other information about the API, e.g: what is CPMain, which procedures contained inside the Console module... The scripts inside bin give very limited information about what is their functionality and how to use them, apart from the obvious are gpcp (compiler), cprun (run), cpmake (make). I currently can't write new code but just compiling examples shipped with gpcp.

**Comment by k-john-gough** [comment]
Hi ruanjiaxing

 

In the release of either of the two distributions (JVM or NET) there is the following documentation –

Getting started guide,

Release notes.

The release notes are about 60 pages long, and explain about the libraries, and also the small differences between the JVM and .NET versions.

 

If you want to know about the internals of the compiler, then my book “Compiling for the .NET Runtime” tells you almost everything.

GPCP (the .NET version) was written as a demonstration program for the .NET system at the time of its release (June 2000). The book was written in 2001, so it is pretty old. 

 

Similarly, the programs GPPG and GPLEX, which are parser-generator and scanner generator tools are only being maintained by me, and not developed further.

 

Hope this helps. If you have any specific questions I will try to answer them. I am not actively developing GPCP any more, but I still fix any issues that happen when Oracle or Microsoft make a change that breaks the build.

 

Best wishes

John

**Comment by ruanjiaxing** [comment]
Sorry. I overlooked it. But what I really want is the html API documents and I found it now. For anyone wanted to view it, it's in gpcp-JVM/symfiles/HtmlBrowseFiles. I will close this issue.
