### ISSUE TITLE
More documents and examples?

### ISSUE THREAD

**Issue by hoper-a11y** [k-john-gough/gpcp#17]
I come from Java so I used to Java OOP. I can't wrap my mind around Oberon/CP's OOP way yet. I found there is no Math module like Oberon07 so we have to use the platform (JVM or CLR) specific functions to do it? I found the html Java binding API document for gpcp JVM but I don't know how to use it. I have no idea what is MathContext and how to use it. Please give me more examples. I just want to use the natural logarithm and square root functions from java math. Thanks.

**Comment by k-john-gough** [comment]
Hi hoper-a11y
Thanks for the question. Yes, it is best to use the native libraries for things like math, unless you want to write a program which will run both on the .NET and the JVM version. In the JVM case it isn't the java/Math library that you want, that is a specialized library used for decimal arithmetic and stuff like that. What you want is the static methods of the Math class of the java.lang library. When you are writing java you get this java.lang without having to ask for it.
I have put together a short program showing how to use the math functions from java.lang in GPCP.
It answers the really important question: which is bigger e^pi, or pi^e.

[DoMath.cp.txt](https://github.com/k-john-gough/gpcp/files/4749527/DoMath.cp.txt)
You will need to change the filename to DoMath.cp to run this.

**Comment by hoper-a11y** [comment]
Thank you.
